### PR TITLE
make ist possible to specify zmq lib path via env variable ZMQ_LIB_PATH

### PR DESCRIPTION
**Pull request by skaes**
Automatic detection of the zmq shared library does not always find
the right version. To solve the problem, we allow the user to specify
the directory in which to find the library.

### CODE REVIEW

**Comment by chuckremes** [comment]
Fix the conflicts after I merged PR #12 and I'll merge this one too. Thanks for the contribution.

**Comment by skaes** [comment]
Fixed the conflicts.

I think you can close https://github.com/chuckremes/ffi-rzmq-core/issues/10 too.

**Comment by chuckremes** [comment]
Thank you for your contribution. 1.0.5 will be released later today.

**Comment by skaes** [comment]
Great! Thx for your quick response.

**Pull request merged**
